default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
#  host: 192.168.1.242
development:
  <<: *default
  database: clicktocal_development



#   DATABASE_URL="mysql2://myuser:mypass@localhost/somedatabase"
#

#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
