default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: userclick
  password: 123456
  socket: /var/run/mysqld/mysqld.sock
  host: 192.168.1.242
development:
  <<: *default
  database: clicktocall



#   DATABASE_URL="mysql2://myuser:mypass@localhost/somedatabase"
#

#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
