default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: userclick
  password: 123456
  socket: /var/run/mysqld/mysqld.sock
development:
  <<: *default
  database: clicktocall

  test:
    <<: *default
    database: clicktocall_test

  production:
    <<: *default
    database: clicktocall_production
    username: clicktocal
    password: <%= ENV['CLICKTOCAL_DATABASE_PASSWORD'] %>
