source 'https://rubygems.org'

gem 'rails', '4.1.4'
gem 'mysql2'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'simple_form', '~> 3.0.2'

gem 'twitter-bootstrap-rails', '~> 3.2.0'

gem 'ip', '~> 0.3.1'

gem 'human_attribute', '~> 0.2.0'

gem 'inherited_resources', '~> 1.5.1'

gem 'actionview-encoded_mail_to', '~> 1.0.4'

gem "enumerate_it"

gem 'better_errors', '~> 2.0.0'
gem 'binding_of_caller', '~> 0.7.2'

gem 'spring',        group: :development

group :development, :test do
  gem 'rspec-rails', '~> 3.0.0'
end

